project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  - cv.qmd
  - writings.qmd

website:
  title: "Timo van Ommeren"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: writings.qmd
        text: Writings
      - href: cv.qmd
        text: CV

format:
  html:
    theme: cosmo

